### ISSUE TITLE
Rebuild PUML Diagram

### ISSUE THREAD

**Issue by ricffb** [elite-se/plantestic-team-4#3]
Rebuild the core elements from Slide 18

**Comment by JuliaMariaBr** [comment]
Open questions:
* What is 'CCCTarget'? How to include this in PUML?
* How to handle multiple activations/deactivations of lifelines? PUML does not support this! (https://plantuml.com/en/sequence-diagram)

Original diagram:
![image](https://user-images.githubusercontent.com/57753393/87035832-2ece4700-c1ea-11ea-8f1a-0edd4d8474d4.png)

Corresponding PUML:
![image](https://user-images.githubusercontent.com/57753393/87039491-7efbd800-c1ef-11ea-957b-ff72d2c6b436.png)
